.\" TH: ヘッダー
.TH "ぬるぽ" 1 "June 2026" "@VERSION@" "User Commands"

.\" SH: セクション
.\" NAME(必須): コマンド名 \- 説明
.SH NAME
ぬるぽ \- ガッ

.\" SYNOPSIS(必須): 書式 使い方
.\" .B: BOLD
.\" []: 省略可能 ちなみに {}: 必須
.SH SYNOPSIS
.B ぬるぽ
[\-\-full] [\-\-version] [\-\-help]

.\" DESCRIPTION(必須): 説明
.SH DESCRIPTION
ぬるぽ すると ｶﾞｯ されます。
ローカルにインターネットが欲しい人のためのコマンドです。

.SH OPTIONS
.\" TP: タグ付き段落
.TP
.B \-\-full
フルAAを表示します。

.TP
.B \-\-version
バージョンを表示します。

.TP
.B \-\-help
ヘルプを表示します。

.\" 終了コード説明
.SH EXIT STATUS
.TP
.B 0
成功
.TP
.B 1
不明なオプションが指定された

.\" サンプル
.SH EXAMPLES

.\" nf: 整形無しテキスト
.nf
$ ぬるぽ
ｶﾞｯ

$ ぬるぽ --full
(AA省略)
.fi

.\" 作者
.SH AUTHOR
GoldenPoisonedApple
